### ISSUE TITLE
Feature Request: Make it work?

### ISSUE THREAD

**Issue by Mycobee** [speedyleion/vobby#1]
would be very tite if you revisted this idea and brought it to life for the 3 oddballs out there searching if this exists?

**Comment by Mycobee** [comment]
While I am making insane github comments, lets go ahead and get this as an nvim lua plugin

**Comment by speedyleion** [comment]
I probable need to go and archive some of my dead repos

I can't remember whey I lost steam here. I think I decided to wait for Vim 8 and the job tasks and then never picked it back up.

Curious why the interest in the infinoted protocol for collaborative editing? 

Or is it just the general idea of an open collaborative editing backend?  
Looking again today, and I'm surprised it still looks pretty fragmented with only IDE specific backends available

**Comment by Mycobee** [comment]
@speedyleion I was setting up a [freedombox](https://www.freedombox.org/) for my family and wanted to play with it...and Vim is hardwired in to my neurons.

This issue is silly, and I was being tongue in cheek. Bless you for your ideas though. May the best ones come to fruition and improve the lives of others :raised_hands: 

All the best :heart:
